library(mlr)
source("R/preprocess_norge_predictive.R")
task_demographic <- makeRegrTask(
  id = "demographic",
  data = numbers_0[, c(5:13, 33:35)],
  target = "value"
)
fv_demographic <- generateFilterValuesData(
  task_demographic,
  method = c("FSelector_information.gain")
)
task_demographic_filtered <- filterFeatures(
  task_demographic,
  fval = fv_demographic,
  threshold = 0.5
)
learners <- list(
  makeLearner("regr.bartMachine"),
  makeLearner("regr.bcart"),
  makeLearner("regr.blm"),
  makeLearner("regr.bst"),
  makeLearner("regr.cforest"),
  makeLearner("regr.crs"),
  makeLearner("regr.ctree"),
  makeLearner("regr.cubist"),
  makeLearner("regr.cvglmnet"),
  makeLearner("regr.earth"),
  makeLearner("regr.evtree"),
  makeLearner("regr.extraTrees"),
  makeLearner("regr.FDboost"),
  makeLearner("regr.fnn"),
  makeLearner("regr.frbs"),
  makeLearner("regr.gamboost"),
  makeLearner("regr.gausspr"),
  makeLearner("regr.gbm"),
  makeLearner("regr.glmboost"),
  makeLearner("regr.glmnet"),
  makeLearner("regr.kknn"),
  makeLearner("regr.ksvm"),
  makeLearner("regr.lm"),
  makeLearner("regr.mars"),
  makeLearner("regr.nnet"),
  makeLearner("regr.pcr"),
  makeLearner("regr.penalized"),
  makeLearner("regr.plsr"),
  makeLearner("regr.randomForestSRC"),
  makeLearner("regr.rpart"),
  makeLearner("regr.RRF"),
  makeLearner("regr.rsm"),
  makeLearner("regr.rvm"),
  makeLearner("regr.xgboost")
)
hyper_pars <- list(
  makeParamSet(
    makeIntegerParam(
      "num_trees",
      13,
      200
    ),
    makeIntegerParam(
      "num_burn_in",
      63,
      1000
    ),
    makeIntegerParam(
      "num_iterations_after_burn_in",
      250,
      4000
    )
  ),
  NA,
  NA,
  makeParamSet(
    makeNumericParam(
      "cost",
      0,
      1
    ),
    makeIntegerParam(
      "mstop",
      13,
      200
    ),
    makeIntegerParam(
      "numsample",
      13,
      200
    ),
    makeIntegerParam(
      "df",
      1,
      16
    ),
    makeIntegerParam(
      "minsplit",
      5,
      80
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "ntree",
      125,
      2000
    ),
    makeIntegerParam(
      "mtry",
      1,
      20
    ),
    makeNumericParam(
      "fraction",
      0.1,
      1
    ),
    makeIntegerParam(
      "minsplit",
      5,
      80
    ),
    makeIntegerParam(
      "minbucket",
      2,
      28
    )
  ),
  NA,
  makeParamSet(
    makeNumericParam(
      "mincriterion",
      0,
      1
    ),
    makeIntegerParam(
      "minsplit",
      5,
      80
    ),
    makeIntegerParam(
      "minbucket",
      2,
      28
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "committees",
      1,
      100
    ),
    makeIntegerParam(
      "rules",
      25,
      400
    ),
    makeNumericParam(
      "extrapolation",
      0,
      100
    )
  ),
  makeParamSet(
    makeNumericParam(
      "alpha",
      0,
      1
    )
  ),
  NA,
  makeParamSet(
    makeIntegerParam(
      "minbucket",
      2,
      28
    ),
    makeIntegerParam(
      "minsplit",
      5,
      80
    ),
    makeIntegerParam(
      "maxdepth",
      3,
      15
    ),
    makeIntegerParam(
      "niterations",
      2500,
      40000
    ),
    makeIntegerParam(
      "ntrees",
      25,
      400
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "ntree",
      125,
      2000
    ),
    makeIntegerParam(
      "mtry",
      1,
      20
    ),
    makeIntegerParam(
      "nodesize",
      2,
      20
    )
  ),
  makeParamSet(
    makeDiscreteParam(
      "family",
      "NBinomial"
    ),
    makeIntegerParam(
      "mstop",
      25,
      400
    ),
    makeNumericParam(
      "nu",
      0,
      1
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "k",
      1,
      12
    )
  ),
  NA,
  makeParamSet(
    makeDiscreteParam(
      "family",
      "NBinomial"
    ),
    makeIntegerParam(
      "mstop",
      25,
      400
    ),
    makeNumericParam(
      "nu",
      0,
      1
    )
  ),
  NA,
  makeParamSet(
    makeIntegerParam(
      "n.trees",
      25,
      400
    ),
    makeIntegerParam(
      "cv.folds",
      0,
      5
    ),
    makeIntegerParam(
      "interaction.depth",
      1,
      2
    ),
    makeNumericParam(
      "alpha",
      0,
      1
    )
  ),
  makeParamSet(
    makeDiscreteParam(
      "family",
      "NBinomial"
    ),
    makeIntegerParam(
      "mstop",
      25,
      400
    ),
    makeNumericParam(
      "nu",
      0,
      1
    )
  ),
  makeParamSet(
    makeNumericParam(
      "alpha",
      0,
      1
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "k",
      2,
      28
    ),
    makeNumericParam(
      "distance",
      1,
      8
    )
  ),
  makeParamSet(
    makeNumericParam(
      "C",
      1,
      4
    ),
    makeNumericParam(
      "nu",
      0.05,
      0.8
    ),
    makeNumericParam(
      "epsilon",
      0.025,
      0.4
    )
  ),
  NA,
  makeParamSet(
    makeIntegerParam(
      "degree",
      1,
      4
    ),
    makeIntegerParam(
      "nk",
      1,
      4
    ),
    makeNumericParam(
      "penalty",
      0.5,
      8
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "size",
      1,
      12
    ),
    makeIntegerParam(
      "maxit",
      25,
      400
    )
  ),
  NA,
  makeParamSet(
    makeNumericParam(
      "lambda1",
      0,
      10
    ),
    makeNumericParam(
      "lambda2",
      0,
      10
    )
  ),
  NA,
  makeParamSet(
    makeIntegerParam(
      "ntree",
      250,
      4000
    ),
    makeIntegerParam(
      "nodesize",
      2,
      20
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "minsplit",
      5,
      80
    ),
    makeIntegerParam(
      "minbucket",
      1,
      10
    ),
    makeIntegerParam(
      "maxcompete",
      1,
      16
    ),
    makeIntegerParam(
      "maxsurrogate",
      2,
      20
    ),
    makeIntegerParam(
      "maxdepth",
      1,
      30
    ),
    makeIntegerParam(
      "xval",
      3,
      40
    )
  ),
  makeParamSet(
    makeIntegerParam(
      "ntree",
      125,
      2000
    ),
    makeIntegerParam(
      "mtry",
      1,
      20
    ),
    makeIntegerParam(
      "nodesize",
      1,
      20
    )
  ),
  NA,
  NA,
  makeParamSet(
    makeNumericParam(
      "eta",
      0,
      1
    ),
    makeNumericParam(
      "gamma",
      0,
      10
    ),
    makeIntegerParam(
      "max_depth",
      2,
      24
    )
  )
)
rdesc <- makeResampleDesc("CV", iters = 2)
ctrl <- makeTuneControlRandom(maxit = 2)
# 385k
# remove node harvest, 31
for (x in 1:34) {
  tuneParams(
    learners[[x]],
    task_demographic_filtered,
    rdesc,
    par.set = hyper_pars[[x]],
    control = ctrl
  )
}
